### ISSUE TITLE
Error 419 on login

### ISSUE THREAD

**Issue by StephenNorris** [alexanderwe/Zeit#10]
Whenever I try to log in I get a blank white screen with “419 | Page Expired” on it.

I can log into the web app fine.

Happens on iOS and iPadOS, both 14.2.

**Comment by MrMage** [comment]
Could you try quitting the Zeit app via the iOS app switcher, then launch it again and immediately try to log in again?

**Comment by alexanderwe** [comment]
@MrMage Thanks for stepping in. 
I tried the login with my users and for them it worked, so I was a little bit lost why this error occurred. Could it be because of some token expired ?

**Comment by MrMage** [comment]
I also tried logging in with Zeit this morning, with no issues.

My best guess would be that Zeit presented an outdated login form whose CSRF token had expired. Force-killing Zeit and relaunching it should cause a fresh login form with a valid CSRF token to be displayed, I hope.

**Comment by StephenNorris** [comment]
That did it! When I relaunched it was already logged in, so I guess the login worked despite the error page.

**Comment by alexanderwe** [comment]
@StephenNorris Great to hear it worked. Strange that the error appeared in the first place since it seems to have worked. Hope this is a one time error. 

If you encounter it again feel free to open an issue again.

**Comment by StephenNorris** [comment]
Thanks for helping out, it's a very useful app.
