### ISSUE TITLE
Can't Get Past Timing Authorize Screen

### ISSUE THREAD

**Issue by semihsezer** [alexanderwe/Zeit#11]
**Describe the bug**

**To Reproduce**
1. Go to Zeit for Timing
2. Click on Login
3. Login with username and password on the embedded browser screen.
4. Timing asks to authorize Zeit.
5. Click Authorize
6. The page stays static and asks me to authorize again, but doesn't redirect me to Zeit. The browser progress bar indicates a reload but I don't really see the page reload.

**Expected behavior**
Webpage redirects me to Zeit successfully, having me logged into Timing.

**Screenshots**
![image](https://github.com/alexanderwe/Zeit/assets/12139945/cbca3662-357f-49e1-96a3-f32da5cbce96)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.2
 - Version of Zeit: 1.1.0

**Additional context**
I do have a professional license and Timing Sync is enabled on my mac.

Thanks!
Semih

**Comment by MrMage** [comment]
Thank you for the report! I had to adjust our web app’s Content Security Policy in order to allow the OAuth flow to complete. Please try again now, and don't forget to close the issue if this resolves it.

**Comment by semihsezer** [comment]
@MrMage the issue is resolved! Thanks for the quick fix! <3
